name: Greetings
on: [push]

jobs:
    build:
        name: Greetings
        runs-on: ubuntu-latest
        steps:
            - name: Hello world
              uses: actions/hello-world-javascript-action@v1
              with:
                who-to-greet: ${{ github.actor }}
              id: hello

            - name: Echo the greeting time
              run: echo 'The time was ${{ steps.hello.outputs.time }}'
              